steps:
### [BUILD CONTAINER] ###
  - name: 'gcr.io/cloud-builders/docker'
    id: build-app-container-image
    entrypoint: /bin/bash
    dir: 'src/heartbeat'
    args: ['-c', 'docker build -t gcr.io/${PROJECT_ID}/heartbeat:build .']

  - name: 'gcr.io/cloud-builders/docker'
    id: list-container-images
    entrypoint: /bin/bash
    dir: 'src/heartbeat'
    args: ['-c', 'docker images']

### [SCAN BUILT CONTAINER] ###
  - name: 'gcr.io/$PROJECT_ID/trivy'
    id: vulnerability-scan-image
    args: ['gcr.io/${PROJECT_ID}/heartbeat:build']

### [VERSION CONTAINER] ###
# To Do: create conditional logic for branching strategy, bump minor in dev, minor/major based on commit message (i.e. git commit -m 'MAJOR|MINOR')
  - name: 'gcr.io/$PROJECT_ID/bumpversion'
    id: version-application-and-build
    entrypoint: /bin/sh
    dir: 'helm-charts/heartbeat'
    secretEnv: ['GITHUB_DEPLOY_KEY']
    args:
    - -c
    - |
      echo "$${GITHUB_DEPLOY_KEY}" >> ~/.ssh/id_rsa && \
      chmod 400 ~/.ssh/id_rsa && \
      git config --global user.email "automation.terracoders@mail.com" && \
      git config --global user.name "automation-terracoders" && \
      bumpversion --verbose patch && \
      git push origin HEAD:main

### [PUBLISH APP] ###
  - name: 'gcr.io/cloud-builders/docker'
    id: publish-app-container
    entrypoint: /bin/bash
    dir: 'helm-charts/heartbeat'
    args:
    - -c
    - |
      docker tag gcr.io/${PROJECT_ID}/heartbeat:build gcr.io/${PROJECT_ID}/heartbeat:$(cat Chart.yaml | grep 'appVersion:' | cut -d' ' -f2) && \
      docker push gcr.io/${PROJECT_ID}/heartbeat:$(cat Chart.yaml | grep 'appVersion:' | cut -d' ' -f2)

availableSecrets:
  secretManager:
  - versionName: projects/791112449288/secrets/GITHUB_AUTOMATION_KEY/versions/1
    env: 'GITHUB_DEPLOY_KEY'