steps:
### [BUILD CONTAINER] ###
  - name: 'gcr.io/cloud-builders/docker'
    id: build-app-container-image
    entrypoint: /bin/bash
    dir: 'src/heartbeat'
    args: ['-c', 'docker build -t gcr.io/${PROJECT_ID}/heartbeat:${_APP_VERSION} .']

  - name: 'gcr.io/cloud-builders/docker'
    id: list-container-images
    entrypoint: /bin/bash
    dir: 'src/heartbeat'
    args: ['-c', 'docker images']

### [SCAN CONTAINER] ###
  - name: 'gcr.io/$PROJECT_ID/trivy'
    id: vulnerability-scan-image
    args: ['gcr.io/${PROJECT_ID}/heartbeat:${_APP_VERSION}']

### [PUBLISH APP] ###
  - name: 'gcr.io/cloud-builders/docker'
    id: publish-app-container
    entrypoint: /bin/bash
    dir: 'src/heartbeat'
    args: ["-c", "docker push gcr.io/${PROJECT_ID}/heartbeat:${_APP_VERSION}"]

substitutions:
  _APP_VERSION: "0.1.13"
