steps:
### [BUILD CONTAINER] ###
  - name: 'gcr.io/cloud-builders/docker'
    id: build-app-container-image
    entrypoint: /bin/bash
    dir: 'src/grafana'
    args: ['-c', 'docker build -t gcr.io/${PROJECT_ID}/grafana:${_APP_VERSION} --build-arg SLACK_ALERT_CHANNEL=$${SLACK_ALERT_CHANNEL} .']
    secretEnv: ['SLACK_ALERT_CHANNEL']

  - name: 'gcr.io/cloud-builders/docker'
    id: list-container-images
    entrypoint: /bin/bash
    dir: 'src/grafana'
    args: ['-c', 'docker images']

### [SCAN CONTAINER] ###
  - name: 'gcr.io/$PROJECT_ID/trivy'
    id: vulnerability-scan-image
    args: ['gcr.io/${PROJECT_ID}/grafana:${_APP_VERSION}']

### [PUBLISH APP] ###
  - name: 'gcr.io/cloud-builders/docker'
    id: publish-app-container
    entrypoint: /bin/bash
    dir: 'src/grafana'
    args: ["-c", "docker push gcr.io/${PROJECT_ID}/grafana:${_APP_VERSION}"]

substitutions:
  _APP_VERSION: "0.1.16"

availableSecrets:
  secretManager:
  - versionName: projects/791112449288/secrets/SLACK_ALERT_CHANNEL/versions/1
    env: 'SLACK_ALERT_CHANNEL'