apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    k8s-apps: http-metrics
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "web-app.selectorLabels" . | nindent 4 }}
