{
 "title": "Ecosystem Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Hello World Web App (Backend)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "summary.up", "id": "1", "type": "max" }
     ],
     "query": "monitor.id: web-app-hello-world-backend",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hello World Web App (Frontend)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "summary.up", "id": "1", "type": "max" }
     ],
     "query": "monitor.id: web-app-hello-world-frontend",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MySQL Database",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "summary.up", "id": "1", "type": "max" }
     ],
     "query": "monitor.id: mysql-blog",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Elasticsearch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "summary.up", "id": "1", "type": "max" }
     ],
     "query": "monitor.id: elasticsearch",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Kibana",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "summary.up", "id": "1", "type": "max" }
     ],
     "query": "monitor.id: kibana",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "summary.up", "id": "1", "type": "max" }
     ],
     "query": "monitor.id: grafana",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Dev Ecosystem Alerts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Web App Backend",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "summary.up", "id": "1", "type": "max" }
     ],
     "query": "monitor.id: web-app-hello-world-backend",
     "timeField": "@timestamp"
    },
    {
     "alias": "Web App Frontend",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "summary.up", "id": "1", "type": "max" }
     ],
     "query": "monitor.id: web-app-hello-world-frontend",
     "timeField": "@timestamp"
    },
    {
     "alias": "MySQL DB",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "summary.up", "id": "1", "type": "max" }
     ],
     "query": "monitor.id: mysql-blog",
     "timeField": "@timestamp"
    },
    {
     "alias": "Elasticsearch",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "summary.up", "id": "1", "type": "max" }
     ],
     "query": "monitor.id: elasticsearch",
     "timeField": "@timestamp"
    },
    {
     "alias": "Kibana",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "summary.up", "id": "1", "type": "max" }
     ],
     "query": "monitor.id: kibana",
     "timeField": "@timestamp"
    },
    {
     "alias": "Grafana",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "summary.up", "id": "1", "type": "max" }
     ],
     "query": "monitor.id: grafana",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}