apiVersion: 1

datasources:
- name: ElasticSearch - Heartbeat
  type: elasticsearch
  access: proxy
  orgId: 1
  url: http://elasticsearch.default.svc.cluster.local:9200
  isDefault: false
  editable: true
  database: heartbeat*
  jsonData:
    esVersion: 70
    logLevelField: ""
    logMessageField: ""
    maxConcurrentShardRequests: 5
    timeField: "@timestamp"