apiVersion: 1

datasources:
- name: ElasticSearch - Heartbeat
  type: elasticsearch
  access: proxy
  orgId: 1
  url: http://elasticsearch.monitoring.svc.cluster.local:9200
  isDefault: false
  editable: true
  database: heartbeat*
  jsonData:
    esVersion: 70
    logLevelField: ""
    logMessageField: ""
    maxConcurrentShardRequests: 5
    timeField: "@timestamp"

- name: Prometheus
  type: prometheus
  orgId: 1
  url: http://prometheus-stack-kube-prom-prometheus.monitoring:9090/
  isDefault: false
  editable: true
  access: direct
  