steps:
### [BUILD APP] ###
  # Install dependencies
  - name: python
    id: install-dependencies
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Run unit tests against app
  - name: python
    id: unit-test-application
    entrypoint: 'bash'
    args: ['-c', 'MYSQL_DATABASE_PASSWORD=$$WEB_APP_DB_PASSWORD DB_HOST=$$DB_HOST python -m pytest']
    secretEnv: ['WEB_APP_DB_PASSWORD']
    env:
      - 'DB_HOST=10.20.208.3'

### [BUILD CONTAINER] ###
  - name: 'gcr.io/cloud-builders/docker'
    id: build-app-container-image
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/web-app:${_APP_VERSION}', '.']

### [SCAN CONTAINER] ###
  - name: gcr.io/cloud-builders/docker
    id: inspect-container
    entrypoint: /bin/bash
    args:
    - -c
    - |
      docker image inspect gcr.io/${PROJECT_ID}/web-app:${_APP_VERSION} --format \
        '{{index .RepoTags 0}}@{{.Id}}' > /workspace/image-digest.txt
      cat image-digest.txt
   
  - name: gcr.io/cloud-builders/gcloud
    id: vulnerability-scan-container
    entrypoint: /bin/bash
    args:
    - -c
    - |
      gcloud artifacts docker images scan gcr.io/${PROJECT_ID}/web-app:${_APP_VERSION} \
      --format='value(response.scan)' > /workspace/scan_id.txt

  - name: gcr.io/cloud-builders/gcloud
    id: vulnerability-severity-check
    entrypoint: /bin/bash
    args:
    - -c
    - | # Check the vulnerabilities and exit if it meets severity level
      gcloud artifacts docker images list-vulnerabilities \
       $(cat /workspace/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
       | if grep -Fxq $_SEVERITY 
         then echo 'Failed vulnerability check'
         exit 1 
         fi

### [PUBLISH APP] ###
images: ['gcr.io/${PROJECT_ID}/web-app:${_APP_VERSION}']

availableSecrets:
  secretManager:
  - versionName: projects/791112449288/secrets/WEB_APP_DB_PASSWORD
    env: 'WEB_APP_DB_PASSWORD'

substitutions:
    _APP_VERSION: 0.1.12
