steps:
### [BUILD APP] ###
  - name: 'python:3.9.2'
    id: install-dependencies
    entrypoint: pip
    dir: 'src/web-app'
    args: ["install", "-r", "requirements.txt", "--user"]

  - name: 'python:3.9.2'
    id: unit-test-application
    entrypoint: 'bash'
    dir: 'src/web-app'
    args: ['-c', 'python -m pytest']

### [VERSION THE BUILD] ###
  - name: 'gcr.io/cloud-builders/git'
    id: fetch-git-info
    args: ["fetch", "--unshallow"]

  - name: 'gcr.io/cloud-builders/git'
    id: generate-build-version
    entrypoint: /bin/bash
    dir: 'src/web-app'
    args: ["-c", "echo ${_MAJOR}.${_MINOR}.$(git rev-list --count HEAD) > APP_VERSION && cat APP_VERSION"]

### [BUILD CONTAINER] ###
  - name: 'gcr.io/cloud-builders/docker'
    id: build-app-container-image
    entrypoint: /bin/bash
    dir: 'src/web-app'
    args: ['-c', 'docker build -t gcr.io/${PROJECT_ID}/web-app:$(cat APP_VERSION) .']

### [SCAN CONTAINER] ###
  - name: 'gcr.io/cloud-builders/gcloud'
    id: vulnerability-scan-container
    entrypoint: /bin/bash
    dir: 'src/web-app'
    args:
    - -c
    - |
      gcloud artifacts docker images scan gcr.io/${PROJECT_ID}/web-app:$(cat APP_VERSION) \
      --format='value(response.scan)' > /workspace/scan_id.txt

  - name: 'gcr.io/cloud-builders/gcloud'
    id: vulnerability-severity-check
    entrypoint: /bin/bash
    dir: 'src/web-app'
    args:
    - -c
    - |
      gcloud artifacts docker images list-vulnerabilities \
       $(cat /workspace/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
       | if grep -Fxq $_SEVERITY 
         then echo 'Failed vulnerability check'
         exit 1 
         fi

### [PUBLISH APP] ###
  - name: 'gcr.io/cloud-builders/docker'
    id: publish-app-container
    entrypoint: /bin/bash
    dir: 'src/web-app'
    args: ["-c", "docker push gcr.io/${PROJECT_ID}/web-app:$(cat APP_VERSION)"]

substitutions:
  _MAJOR: "0"
  _MINOR: "1"
